version: '3.8'

services:
  web-tool:
    container_name: all_in_one_tool
    build: .
    ports:
      - "9090:5000"  # 포트 변경됨
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=dldntjd@D79
      - DB_NAME=tool_db
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped

  db:
    image: mariadb:10.6
    container_name: tool_db
    environment:
      MYSQL_ROOT_PASSWORD: dldntjd@D79
      MYSQL_DATABASE: tool_db
    ports:
      - "9911:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

volumes:
  db_data: